services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agriculture_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: agriculture_db
    ports:
      - "3002:3002"
    command: sh -c "until pg_isready -h postgres -p 5432; do sleep 2; done && npm run migration:run && npm run test && npm run start:prod"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3002
    ports:
      - "3000:3000"
    command: sh -c "npm run build && npm run preview -- --host 0.0.0.0 --port 3000"

volumes:
  pgdata:
